version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ochi1000/udagram-api-feed:v1
      - image: ochi1000/udagram-api-user:v1
      - image: ochi1000/udagram-frontend:v1
      - image: ochi1000/reverseproxy:v1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: docker compose up
      - run: docker push ochi1000/udagram-api-feed:v1
      - run: docker push ochi1000/udagram-api-user:v1
      - run: docker push ochi1000/udagram-frontend:v1
      - run: docker push ochi1000/reverseproxy:v1

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
