version: 2.1

jobs:
  insta-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- The images are Building --------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed ochi1000/udagram-api-feed:v1
            
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user ochi1000/udagram-api-user:v1
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend ochi1000/udagram-frontend:v1
            
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy ochi1000/reverseproxy:v1

            echo "------ All images successfully built--------"

            echo "-------- Login to DockerHub--------"

            docker login -u $DOCKER_USERNAME -p $DOCKERPASS

            echo "------- Pushing images to dockerhub ------"

            docker push ochi1000/udagram-api-feed:v1
            docker push ochi1000/udagram-api-user:v1
            docker push ochi1000/udagram-frontend:v1
            docker push ochi1000/reverseproxy:v1

workflows:
  default:
    jobs:
      - insta-app
      - build-docker:
          requires: [insta-app]
