apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    service: backend-feed