name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push Docker udagram-frontend image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        push: true
        image: ochi1000/udagram-frontend
        
    - name: Build and push Docker udagram-api-user image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        push: true
        image: ochi1000/udagram-api-user
        
    - name: Build and push Docker udagram-api-feed image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        push: true
        image: ochi1000/udagram-api-feed
        
    - name: Build and push Docker udagram-reverseproxy image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        push: true
        image: ochi1000/reverseproxy
